# conf/config.yaml

defaults:
  - _self_

hydra:
  job:
    name: default
  
  run:
    dir: outputs/${now:%Y-%m-%d}/${hydra.job.name}

  sweep:
    dir: multirun/${now:%Y-%m-%d}/${hydra.job.name}
    subdir: ${hydra.job.num}

data:
<<<<<<< HEAD
  root_dir: /home/cpsc452_tcm57/452_final_project
=======
  root_dir: /home/tcm57/452_final_project
>>>>>>> 6f68613 (minor changes)
  data_dir: ${data.root_dir}/data
  batch_size: 256
  fraction_of_data: 0.1
  composition_embedding: composition1D
  simulation: 
    crop_start: 4000
    crop_stop: 4000
    noise_range: 0.4
    drop_width: 1000
    drop_freq: 2

model:
  in_channels: 1
  output_dim: 230
  composition_model: null #note that this MUST match the composition embedding (otherwise, things will break)

training:
  max_epochs: 200
  lr: 0.0002
  weight_decay: 0
